export interface InvoiceTemplateConfig {
  id: string;
  name: string;
  category: 'moderno' | 'clasico' | 'minimalista' | 'elegante' | 'corporativo' | 'creativo';
  accentColor: string;
  secondaryColor: string;
  headerLayout: 'classic' | 'left' | 'centered';
  showFooter: boolean;
  headerStyle: 'solid' | 'gradient' | 'split';
  tableHeaderStyle: 'filled' | 'outlined' | 'minimal';
  fontFamily: string;
}

export const INVOICE_TEMPLATES: InvoiceTemplateConfig[] = [
  // ═══════════════════════════════════════════════
  // MODERNO (8)
  // ═══════════════════════════════════════════════
  {
    id: 'moderno-fresco',
    name: 'Fresco Corporativo',
    category: 'moderno',
    accentColor: '#0891b2',
    secondaryColor: '#06b6d4',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'moderno-oceano',
    name: 'Océano Digital',
    category: 'moderno',
    accentColor: '#1d4ed8',
    secondaryColor: '#06b6d4',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Space Grotesk, system-ui, sans-serif',
  },
  {
    id: 'moderno-neon',
    name: 'Neón Tech',
    category: 'moderno',
    accentColor: '#7c3aed',
    secondaryColor: '#a855f7',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'filled',
    fontFamily: 'JetBrains Mono, monospace',
  },
  {
    id: 'moderno-aurora',
    name: 'Aurora Boreal',
    category: 'moderno',
    accentColor: '#059669',
    secondaryColor: '#3b82f6',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'moderno-circuito',
    name: 'Circuito',
    category: 'moderno',
    accentColor: '#f97316',
    secondaryColor: '#1e293b',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'split',
    tableHeaderStyle: 'filled',
    fontFamily: 'JetBrains Mono, monospace',
  },
  {
    id: 'moderno-pixel',
    name: 'Pixel',
    category: 'moderno',
    accentColor: '#ef4444',
    secondaryColor: '#f97316',
    headerLayout: 'left',
    showFooter: false,
    headerStyle: 'solid',
    tableHeaderStyle: 'minimal',
    fontFamily: 'JetBrains Mono, monospace',
  },
  {
    id: 'moderno-futuro',
    name: 'Futuro',
    category: 'moderno',
    accentColor: '#06b6d4',
    secondaryColor: '#22d3ee',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Space Grotesk, system-ui, sans-serif',
  },
  {
    id: 'moderno-nebulosa',
    name: 'Nebulosa',
    category: 'moderno',
    accentColor: '#9333ea',
    secondaryColor: '#ec4899',
    headerLayout: 'classic',
    showFooter: false,
    headerStyle: 'gradient',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Inter, system-ui, sans-serif',
  },

  // ═══════════════════════════════════════════════
  // CLÁSICO (8)
  // ═══════════════════════════════════════════════
  {
    id: 'clasico-tradicional',
    name: 'Tradicional',
    category: 'clasico',
    accentColor: '#1e3a5f',
    secondaryColor: '#2563eb',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'clasico-herencia',
    name: 'Herencia',
    category: 'clasico',
    accentColor: '#9f1239',
    secondaryColor: '#be123c',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'clasico-occidente',
    name: 'Occidente',
    category: 'clasico',
    accentColor: '#166534',
    secondaryColor: '#15803d',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'clasico-espanol',
    name: 'Clásico Español',
    category: 'clasico',
    accentColor: '#dc2626',
    secondaryColor: '#1e293b',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'split',
    tableHeaderStyle: 'filled',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'clasico-biblioteca',
    name: 'Biblioteca',
    category: 'clasico',
    accentColor: '#92400e',
    secondaryColor: '#b45309',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'clasico-grabado',
    name: 'Grabado',
    category: 'clasico',
    accentColor: '#1e293b',
    secondaryColor: '#d4a017',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'split',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'clasico-fundacion',
    name: 'Fundación',
    category: 'clasico',
    accentColor: '#475569',
    secondaryColor: '#64748b',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'clasico-legado',
    name: 'Legado',
    category: 'clasico',
    accentColor: '#c2410c',
    secondaryColor: '#ea580c',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'filled',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },

  // ═══════════════════════════════════════════════
  // MINIMALISTA (9)
  // ═══════════════════════════════════════════════
  {
    id: 'minimal-limpio',
    name: 'Limpio',
    category: 'minimalista',
    accentColor: '#18181b',
    secondaryColor: '#27272a',
    headerLayout: 'left',
    showFooter: false,
    headerStyle: 'solid',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'minimal-byn',
    name: 'Blanco y Negro',
    category: 'minimalista',
    accentColor: '#52525b',
    secondaryColor: '#71717a',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'minimal-linea-fina',
    name: 'Línea Fina',
    category: 'minimalista',
    accentColor: '#3b82f6',
    secondaryColor: '#60a5fa',
    headerLayout: 'left',
    showFooter: false,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'minimal-espacio',
    name: 'Espacio',
    category: 'minimalista',
    accentColor: '#a1a1aa',
    secondaryColor: '#d4d4d8',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'minimal-puro',
    name: 'Puro',
    category: 'minimalista',
    accentColor: '#2563eb',
    secondaryColor: '#3b82f6',
    headerLayout: 'centered',
    showFooter: false,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'minimal-simple',
    name: 'Simple',
    category: 'minimalista',
    accentColor: '#0f172a',
    secondaryColor: '#334155',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'minimal-diafano',
    name: 'Diáfano',
    category: 'minimalista',
    accentColor: '#64748b',
    secondaryColor: '#94a3b8',
    headerLayout: 'left',
    showFooter: false,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'minimal-esencial',
    name: 'Esencial',
    category: 'minimalista',
    accentColor: '#18181b',
    secondaryColor: '#3f3f46',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'minimal-claridad',
    name: 'Claridad',
    category: 'minimalista',
    accentColor: '#0d9488',
    secondaryColor: '#14b8a6',
    headerLayout: 'left',
    showFooter: false,
    headerStyle: 'solid',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Inter, system-ui, sans-serif',
  },

  // ═══════════════════════════════════════════════
  // ELEGANTE (8)
  // ═══════════════════════════════════════════════
  {
    id: 'elegante-champan',
    name: 'Champán',
    category: 'elegante',
    accentColor: '#b8860b',
    secondaryColor: '#d4a017',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'elegante-dorado',
    name: 'Dorado',
    category: 'elegante',
    accentColor: '#92400e',
    secondaryColor: '#d4a017',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'filled',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'elegante-lujo',
    name: 'Lujo',
    category: 'elegante',
    accentColor: '#18181b',
    secondaryColor: '#d4a017',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'split',
    tableHeaderStyle: 'filled',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'elegante-prestigio',
    name: 'Prestigio',
    category: 'elegante',
    accentColor: '#881337',
    secondaryColor: '#9f1239',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'elegante-selecto',
    name: 'Selecto',
    category: 'elegante',
    accentColor: '#27272a',
    secondaryColor: '#a1a1aa',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'split',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'elegante-opulencia',
    name: 'Opulencia',
    category: 'elegante',
    accentColor: '#d4a017',
    secondaryColor: '#18181b',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'filled',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'elegante-brillo',
    name: 'Brillo',
    category: 'elegante',
    accentColor: '#71717a',
    secondaryColor: '#d4d4d8',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  {
    id: 'elegante-majestuoso',
    name: 'Majestuoso',
    category: 'elegante',
    accentColor: '#1e40af',
    secondaryColor: '#d4a017',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'split',
    tableHeaderStyle: 'filled',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },

  // ═══════════════════════════════════════════════
  // CORPORATIVO (9)
  // ═══════════════════════════════════════════════
  {
    id: 'corp-empresa',
    name: 'Empresa',
    category: 'corporativo',
    accentColor: '#1d4ed8',
    secondaryColor: '#2563eb',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'corp-oficina',
    name: 'Oficina',
    category: 'corporativo',
    accentColor: '#52525b',
    secondaryColor: '#71717a',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'corp-negocio',
    name: 'Negocio',
    category: 'corporativo',
    accentColor: '#166534',
    secondaryColor: '#15803d',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'corp-institucion',
    name: 'Institución',
    category: 'corporativo',
    accentColor: '#1e3a8a',
    secondaryColor: '#1d4ed8',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'corp-plus',
    name: 'Corporativo Plus',
    category: 'corporativo',
    accentColor: '#1e40af',
    secondaryColor: '#3b82f6',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'split',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'corp-ejecutivo',
    name: 'Ejecutivo',
    category: 'corporativo',
    accentColor: '#374151',
    secondaryColor: '#4b5563',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'corp-profesional',
    name: 'Profesional',
    category: 'corporativo',
    accentColor: '#475569',
    secondaryColor: '#64748b',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'corp-directorio',
    name: 'Directorio',
    category: 'corporativo',
    accentColor: '#1e3a5f',
    secondaryColor: '#0f766e',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'corp-sede',
    name: 'Sede',
    category: 'corporativo',
    accentColor: '#0369a1',
    secondaryColor: '#0ea5e9',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },

  // ═══════════════════════════════════════════════
  // CREATIVO (8)
  // ═══════════════════════════════════════════════
  {
    id: 'crea-atardecer',
    name: 'Atardecer',
    category: 'creativo',
    accentColor: '#ea580c',
    secondaryColor: '#ec4899',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'crea-tropical',
    name: 'Tropical',
    category: 'creativo',
    accentColor: '#16a34a',
    secondaryColor: '#06b6d4',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'crea-lavanda',
    name: 'Lavanda',
    category: 'creativo',
    accentColor: '#8b5cf6',
    secondaryColor: '#a78bfa',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'crea-fuego',
    name: 'Fuego',
    category: 'creativo',
    accentColor: '#dc2626',
    secondaryColor: '#f97316',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'filled',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'crea-bosque',
    name: 'Bosque',
    category: 'creativo',
    accentColor: '#15803d',
    secondaryColor: '#0d9488',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'crea-coral',
    name: 'Coral',
    category: 'creativo',
    accentColor: '#f43f5e',
    secondaryColor: '#fb7185',
    headerLayout: 'centered',
    showFooter: true,
    headerStyle: 'solid',
    tableHeaderStyle: 'outlined',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'crea-medianoch',
    name: 'Medianoche',
    category: 'creativo',
    accentColor: '#0f172a',
    secondaryColor: '#06b6d4',
    headerLayout: 'classic',
    showFooter: true,
    headerStyle: 'split',
    tableHeaderStyle: 'filled',
    fontFamily: 'JetBrains Mono, monospace',
  },
  {
    id: 'crea-estrella',
    name: 'Estrella',
    category: 'creativo',
    accentColor: '#7c3aed',
    secondaryColor: '#f43f5e',
    headerLayout: 'left',
    showFooter: true,
    headerStyle: 'gradient',
    tableHeaderStyle: 'minimal',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'Todas', icon: 'fa-grid-2' },
  { id: 'moderno', label: 'Moderno', icon: 'fa-bolt' },
  { id: 'clasico', label: 'Clásico', icon: 'fa-landmark' },
  { id: 'minimalista', label: 'Minimalista', icon: 'fa-minus' },
  { id: 'elegante', label: 'Elegante', icon: 'fa-gem' },
  { id: 'corporativo', label: 'Corporativo', icon: 'fa-briefcase' },
  { id: 'creativo', label: 'Creativo', icon: 'fa-palette' },
] as const;

export function getTemplateById(id: string): InvoiceTemplateConfig {
  return INVOICE_TEMPLATES.find((t) => t.id === id) || INVOICE_TEMPLATES[0];
}
